In [7]:
import pandas as pd
import os
import apikeys
import requests
import json
import csv

In [8]:
#import file for Nominees list

file = os.path.join('Updated_List_Nominations.csv')

nominees_list = pd.read_csv(file)
nominees_list.head()

,Year,RECORD OF THE YEAR,ROY ARTIST,BEST NEW ARTIST,SONG OF THE YEAR,SOY ARTIST
0,2018,Redbone,Childish Gambino,Alessia Cara,Despacito,Luis Fonsi Daddy Yankee Justin Bieber
1,2018,Despacito,Luis Fonsi Daddy Yankee Justin Bieber,Khalid,4:44,JAY-Z
2,2018,The Story of O.J.,JAY-Z,Lil Uzi Vert,Issues,Julia Michaels
3,2018,Humble,Kendrick Lamar,Julia Michaels,1-800-273-8255,Logic Alessia Cara Khalid
4,2018,24k Magic,Bruno Mars,SZA,That's What I Like,Bruno Mars

In [13]:
# Combine related columns and create a new combined column

nominees_list['ROY Combined'] = nominees_list['RECORD OF THE YEAR'] + " " + nominees_list['ROY ARTIST']
nominees_list['SOY Combined'] = nominees_list['SONG OF THE YEAR'] + " " + nominees_list['SOY ARTIST']

nominees_list.head()

# Generate a new list with combined data

rev_nominees_list = nominees_list[["Year", "ROY Combined", "SOY Combined", "BEST NEW ARTIST"]]

rev_nominees_list.head()

,Year,ROY Combined,SOY Combined,BEST NEW ARTIST
0,2018,Redbone Childish Gambino,Despacito Luis Fonsi Daddy Yankee Justin Bieber,Alessia Cara
1,2018,Despacito Luis Fonsi Daddy Yankee Justin Bieber,4:44 JAY-Z,Khalid
2,2018,The Story of O.J. JAY-Z,Issues Julia Michaels,Lil Uzi Vert
3,2018,Humble Kendrick Lamar,1-800-273-8255 Logic Alessia Cara Khalid,Julia Michaels
4,2018,24k Magic Bruno Mars,That's What I Like Bruno Mars,SZA

In [16]:
#Create a DataFrame for the Nominees list

rev_nominees_list_df = pd.DataFrame(rev_nominees_list)
rev_nominees_list_df.head()

#Split the DataFrame by category
#Record of the Year
records_list_df = rev_nominees_list_df[["Year", "ROY Combined"]]
records_list_df.head()

#Split the DataFrame by category
new_artist_list_df = rev_nominees_list_df[["Year", "BEST NEW ARTIST"]]
new_artist_list_df.head()

#Split the DataFrame by category
song_list_df = rev_nominees_list_df[["Year", "SOY Combined"]]
song_list_df.head()

   Year                                     SOY Combined
0  2018  Despacito Luis Fonsi Daddy Yankee Justin Bieber
1  2018                                       4:44 JAY-Z
2  2018                            Issues Julia Michaels
3  2018         1-800-273-8255 Logic Alessia Cara Khalid
4  2018                    That's What I Like Bruno Mars

In [17]:
#import file for Winners list

file = os.path.join('Grammy_winner_list.csv')

winners_list = pd.read_csv(file)
winners_list.head()

#Create a DataFrame for the Nominees list

winners_list_df = pd.DataFrame(winners_list)
winners_list_df

#Split the DataFrame by category
#Record of the Year
records_winner_list_df = winners_list_df[["Year", "RECORD OF THE YEAR"]]
records_winner_list_df.head()

#Artist of the Year
newartist_winner_list_df = winners_list_df[["Year", "BEST NEW ARTIST"]]
newartist_winner_list_df.head()

#Song of the Year
song_winner_list_df = winners_list_df[["Year", "SONG OF THE YEAR"]]
song_winner_list_df.head()

   Year                  SONG OF THE YEAR
0  2017                             Hello
1  2016                 Thinking Out Loud
2  2015  Stay With Me (Darkchild Version)
3  2014                            Royals
4  2013                      We Are Young